version: "3.8"

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/base:debian
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    privileged: true
    volumes:
      - ..:/workspaces/template-repository:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
